name: Variables and Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "username=${USERNAME} password=${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
